/* ICT2622 original offline mastery content. Shared engine remains module-independent. */
(function () {
  "use strict";
  const term=(term,meaning)=>({term,meaning});
  const ch=(title,topics)=>({title,topics});
  const topic=(id,title,summary,terms,notes,exercises)=>({
    id,title,summary,reference:"ICT2622 original practice guide · "+title,
    terms,notes,exercises
  });
  const q=(id,prompt,options,answer,explanation,studentNote,caseStudy)=>({
    id,kind:"choice",prompt,options,answer,explanation,studentNote,
    ...(caseStudy?{caseStudy}:{})
  });
  const order=(id,prompt,items,answer,explanation,studentNote)=>({
    id,kind:"sequence",prompt,items,answer,explanation,studentNote
  });
  window.MasteryModules=window.MasteryModules || [];
  window.MasteryModules.push({
    id:"ict2622",name:"ICT2622",
    sourceFiles:[
      "ict2622-jan-feb-2025-practice.json",
      "ict2622-oct-nov-2025-practice.json",
      "ict2622-jan-feb-2026-practice.json",
      "ict2622-assessment-1-2026-practice.json",
      "ict2622-assessment-2-2026-practice.json",
      "ict2622-practical-skills-lab.json"
    ],
    chapters:[
      ch("1 · Analysis and requirements",[
        topic("oo1-vision","System vision and development cycles",
          "Analysis clarifies the problem and what the proposed system should accomplish. A system vision summarises the problem, important capabilities and business benefit. Iterative development refines working increments using feedback.",
          [term("System vision","Short, high-level reason and value of a new system."),
           term("Iteration","A cycle of building and reviewing part of a solution.")],
          ["The vision is not a complete source-code or database schema.","An agile or iterative project may adjust requirements after each review."],
          [q("oo1a","A sponsor requests a one-page reason for introducing a new booking app. What belongs there?",
            ["The problem, main capabilities and expected benefit","Every SQL statement","Only developer names"],0,
            "Those three high-level elements help stakeholders understand the proposed system.",
            "A detailed implementation choice can change later; keep the vision understandable."),
           q("oo1b","What normally follows a short iteration?",["An increment that can be checked","A promise to avoid all feedback","An automatic full system replacement"],0,
            "An increment enables earlier feedback and correction.",
            "Working software still needs testing; partial increments need not be the entire product.")]),
        topic("oo1-requirements","Functional needs and user goals",
          "A functional requirement describes something the solution must do. Non-functional requirements constrain qualities such as security, capacity and performance. A user goal is an outcome achieved with the system.",
          [term("Functional requirement","A required function or service."),
           term("Non-functional requirement","A quality or constraint such as response time."),
           term("Actor goal","A useful outcome an interacting role seeks.")],
          ["'Reserve a book' is a function; 'respond within two seconds' is a quality target.","Identify goals before designing all the screens."],
          [q("oo1c","Which is a measurable non-functional requirement?",
            ["Search returns within two seconds under normal load","Customer can reserve a book","Staff can add a journal"],0,
            "The statement measures how well the search should work, not another function.",
            "Use specific values and conditions so that quality claims can be tested."),
           q("oo1d","Which phrase best identifies a user goal?",["Customer confirms an order","Customer taps a blue rectangle","Button has a shadow"],0,
            "A goal describes the meaningful outcome of interaction.",
            "A button tap is just one step in achieving the goal.")])
      ]),
      ch("2 · Use cases and actors",[
        topic("oo2-actors","Find actors and their use cases",
          "Actors are external roles such as Customer, Staff or a linked payment service. Use cases are named goals that a role performs using the system. A use-case diagram puts goals inside a system boundary and actors outside.",
          [term("Actor","An external role that uses or supports a system."),
           term("Use case","A useful system-supported goal."),
           term("System boundary","The box separating the system's functions from its outside roles.")],
          ["A use-case diagram is not the chronological workflow; that belongs in an activity diagram.",
           "Multiple actors may be linked to the same use case."],
          [q("oo2a","A courier updates delivery status and a customer tracks it. Which UML form is most suitable to show who uses each goal?",
            ["Use case diagram","CPU block diagram","Only a database index"],0,
            "Use case diagrams show the functions accessible to each actor.",
            "Use verb phrases such as Update status rather than generic labels such as Screen 4."),
           q("oo2b","Where should the Customer actor appear in a normal use-case diagram?",
            ["Outside the system boundary","As a use-case oval inside it","Inside a database table box"],0,
            "Actors represent roles that interact with the system from outside the boundary.",
            "A domain class named Customer is a different representation of a related real-world idea.")]),
        topic("oo2-developed","Fully developed use case descriptions",
          "A full use case goes beyond listing features: identify the name and actor, trigger and preconditions, numbered main success steps, alternatives/exceptions and postconditions.",
          [term("Precondition","State required before a use case starts."),
           term("Trigger","Event that begins the use case."),
           term("Alternative flow","A meaningful different path, for example failed payment.")],
          ["Make every step clear about who acts: the person or the system.",
           "Failed authorisation should not accidentally lead to a success postcondition."],
          [order("oo2c","Choose a useful order for drafting a full use case.",
            ["Name, actor and trigger","Preconditions","Main success steps","Alternatives and exceptions","Postconditions"],
            ["Name, actor and trigger","Preconditions","Main success steps","Alternatives and exceptions","Postconditions"],
            "This structure makes the normal path, failure cases and final result easy to check.",
            "A use case can contain additional fields, but these are the core elements a learner should practise."),
           q("oo2d","Payment is refused during Checkout. Where do you document the response?",["An alternative or exception flow","Only the system name","Only the class name"],0,
            "A refused payment changes the main success path and needs a stated response.",
            "Record a clear failure postcondition so no successful order is created accidentally.")])
      ]),
      ch("3 · UML structure and data",[
        topic("oo3-domain","Classes and relationships",
          "A domain class represents a business concept. Each class may contain attributes; associations connect relevant classes and multiplicity states the number of allowed instances.",
          [term("Class","Description of a type of object in the problem domain."),
           term("Attribute","Information held about an object."),
           term("Multiplicity","Permitted number of links on an association end.")],
          ["Model business nouns such as Student, Registration and Module.","A screen or repository belongs in other diagrams unless it is an actual business-domain concept."],
          [q("oo3a","A Customer may place many Orders, but each Order belongs to one Customer. Which is the correct multiplicity?",
            ["Customer 1 — 0..* Order","Customer 0..* — 0..* Order always","Customer 0 — 0 Order"],0,
            "One Customer can link to zero or many Orders; an Order links to one Customer.",
            "Read the permitted count on each end rather than guessing from visual placement."),
           q("oo3b","A class records an item's price and availability. What are those values?",["Attributes","Actors","Use-case arrows"],0,
            "They describe properties of an Item instance.",
            "calculatePrice() would be an operation rather than a stored attribute.")]),
        topic("oo3-er","ERD and relational mapping",
          "An ERD describes entities, keys and cardinalities. A many-to-many relationship usually requires an associative table. A foreign key links to another table's key.",
          [term("Primary key","Identifier of a table row."),
           term("Foreign key","Field referring to a key in a related table."),
           term("Associative table","Table representing a many-to-many relationship.")],
          ["Use 0..* when the associated entity can have no instances as well as many.","A composite key is a key formed from more than one column."],
          [q("oo3c","Many Students choose many Courses. What relational structure can store each enrolment?",["An associative Enrolment table","One comma-separated course field","No relationship"],0,
            "The associative table holds references to both participating parent tables.",
            "It can also contain attributes such as enrolmentDate and grade."),
           q("oo3d","In Order, the customerId refers to Customer's primary key. What is customerId in Order?",["Foreign key","Always a timestamp","Use-case trigger"],0,
            "It references a key in another table and helps enforce a relationship.",
            "Foreign keys are different from the business concept of a customer role.")])
      ]),
      ch("4 · Workflow diagrams",[
        topic("oo4-activity","Action, decision and guard flows",
          "An activity diagram maps a workflow: initial circle, actions, arrows, decision diamonds with condition labels and one or more final nodes.",
          [term("Initial node","Filled circle where the workflow begins."),
           term("Decision","A diamond where the flow selects a branch."),
           term("Guard","Condition label on a branch such as [paid].")],
          ["Activities show order and conditions; use-case diagrams show who needs system goals.",
           "An arrow should not jump from [payment failed] to preparing goods."],
          [order("oo4a","Put the successful checkout flow in a sensible sequence.",
            ["Start","Select item","Confirm cart","Approve payment","Record order","End"],
            ["Start","Select item","Confirm cart","Approve payment","Record order","End"],
            "The order must be recorded only after the payment outcome permits it.",
            "Also practise drawing an alternate [payment rejected] branch."),
           q("oo4b","Which symbol most clearly represents a [valid]/[invalid] branch?",["Diamond decision node","Actor stick figure","Domain attribute"],0,
            "The decision node separates paths based on conditions.",
            "Label both exits so the reader can follow the flow.")]),
        topic("oo4-process","Distinguish UML diagram types",
          "Use-case diagrams map actor goals, activity diagrams map workflows, class diagrams map static structure, and sequence diagrams map messages between objects over time.",
          [term("Sequence diagram","Messages exchanged between object lifelines over time."),
           term("Domain class diagram","Business concepts and structural associations.")],
          ["Choose the diagram based on the question's verb: who uses? what happens next? what things exist? who sends which message?",
           "A sketch with disconnected shapes is not a complete diagram."],
          [q("oo4c","A question asks for chronological messages from View to Controller to Order. Which type fits?",["Sequence diagram","Domain class diagram","Package only"],0,
            "A sequence diagram uses participant lifelines and message arrows over time.",
            "Time usually moves down the diagram."),
           q("oo4d","A question asks for business entities, attributes and associations. Which fits?",["Domain class diagram","Activity diagram only","Use-case oval list only"],0,
            "Class diagrams show static structure and relationships.",
            "Activity arrows describe process flow, not association multiplicity.")])
      ]),
      ch("5 · OO design quality and layers",[
        topic("oo5-layers","View, domain and data access responsibilities",
          "The view presents and captures information, domain objects handle business rules, and persistence/data-access services store or retrieve records.",
          [term("View layer","Interaction with user interface."),
           term("Domain layer","Core business meaning and behaviour."),
           term("Data access layer","Persistence and retrieval concerns.")],
          ["Avoid mixing direct SQL, pricing business rules and button drawing in one class.",
           "The exact framework can change, but separation of responsibilities remains helpful."],
          [q("oo5a","Which layer should decide whether a RepairRequest is cancellable under business rules?",
            ["Domain layer","Button styling only","Connection pooling only"],0,
            "A repair request's valid state transitions are domain behaviour.",
            "The view may call the operation but should not own all the rules."),
           q("oo5b","Which layer typically reads an Order row from the DBMS?",["Data access layer","External Customer actor","Activity final node"],0,
            "Persistence services are responsible for storing and retrieving domain data.",
            "An Order is a business object, while a repository helps it survive across sessions.")]),
        topic("oo5-grasp","Cohesion, coupling and design responsibility",
          "High cohesion keeps related tasks together. Low coupling limits dependency. Information Expert assigns work to a class that already knows the needed data; indirection and Protected Variations can shield changeable services.",
          [term("Cohesion","How closely a class's duties belong together."),
           term("Coupling","How dependent parts are on one another."),
           term("Information Expert","Give responsibility to the object with relevant information.")],
          ["A change in a payment gateway should not require rewriting every order business rule.",
           "Design patterns and intermediary classes are tools, not goals in themselves."],
          [q("oo5c","An Order owns OrderLines and can calculate their total. Which assignment principle supports this?",
            ["Information Expert","Random delegation","Disk replication"],0,
            "Order has the information needed to calculate the sum.",
            "Do not put every business calculation into a display widget."),
           q("oo5d","A service depends on a stable PaymentGateway interface rather than a specific vendor library. What is reduced?",
            ["Coupling to the vendor","The number of valid user goals","Need for any testing"],0,
            "The stable interface isolates change in the external provider.",
            "An extra interface only helps when it represents a meaningful boundary.")])
      ]),
      ch("6 · Practical solution writing",[
        topic("oo6-responsibility","Tables and structured answers",
          "A structured answer can pair classes with attributes, responsibilities, multiplicities or layer placement. Compare each cell with the question's stated requirement rather than writing long unsupported prose.",
          [term("Responsibility table","A compact way to map concepts to their required duties."),
           term("Partial marks","Credit for independently correct parts even if other cells are wrong.")],
          ["For a fixed-answer exercise, complete every required cell; blank cells cannot earn marks.",
           "For open-ended table design, the rubric should check meaning rather than exact wording."],
          [q("oo6a","Which domain class is the natural home for a repair's current status and reported fault?",
            ["RepairRequest","DesktopView","EmailSender"],0,
            "A request records its own business state and reported problem.",
            "A UI can display status, but its domain source should be the request."),
           q("oo6b","An answer grid has four independently marked rows. What helps earn marks when uncertain?",
            ["Complete every cell you can justify","Leave every cell blank","Replace it with an unrelated essay"],0,
            "Each correctly completed expected cell can contribute to the available marks.",
            "Read the supplied vocabulary and headings before choosing words.")]),
        topic("oo6-code","Commands, code and safe checks",
          "A one-line command with a known expected answer may be checked locally. Open-ended code or pseudocode should be marked against a clear rubric; entered code must not be executed on the user's machine by the simulator.",
          [term("Pseudocode","Language-neutral outline of an algorithm."),
           term("Rubric","List of required behaviours or concepts used to assess an answer.")],
          ["For input validation, check that a record exists before reading its fields.",
           "Use commands such as SELECT ... WHERE ... to demonstrate exact query structure when asked."],
          [q("oo6c","A function should deny approval when a quote is missing. Which test must run before quote.expiresAt is accessed?",
            ["Check that quote exists","Always read expiresAt first","Delete the request"],0,
            "The existence check prevents a null-reference failure.",
            "Equivalent safe pseudocode can be valid even when the learner's variable names differ."),
           q("oo6d","A SELECT statement should return only pending orders. What SQL clause applies a row condition?",
            ["WHERE","GROUP BY only","INSERT INTO"],0,
            "WHERE filters rows using a predicate.",
            "A command answer should not require paid AI if a precise expected syntax is supplied.")])
      ])
    ]
  });
}());
