/* Subject data only. Other modules register the same format; the shared
   engine must not know what INF3708, WBS, PERT or RACI mean. Values were
   checked against INF3708 Summary.pdf; this is a practice set, not a
   replacement for the complete source document or official study guide. */
(function () {
  "use strict";
  function term(term, meaning) { return { term: term, meaning: meaning }; }
  function topic(id, title, summary, reference, terms, notes, exercises) {
    return { id: id, title: title, summary: summary, reference: reference,
      terms: terms || [], notes: notes || [], exercises: exercises || [] };
  }
  function chapter(title, topics) { return { title: title, topics: topics }; }
  function quiz(id, prompt, options, answer, explanation, studentNote, extra) {
    return Object.assign({ id: id, kind: "choice", prompt: prompt, options: options,
      answer: answer, explanation: explanation, studentNote: studentNote }, extra || {});
  }
  function calc(id, prompt, formula, examples, explanation, studentNote, hint, tolerance) {
    return { id: id, kind: "number", prompt: prompt, formula: formula,
      examples: examples, explanation: explanation, studentNote: studentNote,
      hint: hint, tolerance: tolerance === undefined ? 0.05 : tolerance };
  }
  function sequence(id, prompt, items, answer, explanation, studentNote) {
    return { id: id, kind: "sequence", prompt: prompt, items: items,
      answer: answer, explanation: explanation, studentNote: studentNote };
  }
  var network = {
    alt: "Activity network. A five days and B ten days both lead to C seven days, then finish.",
    nodes: [
      { id: "A", label: "A · 5d", x: 17, y: 24 },
      { id: "B", label: "B · 10d", x: 17, y: 75 },
      { id: "C", label: "C · 7d", x: 60, y: 50 },
      { id: "F", label: "Finish", x: 88, y: 50 }
    ],
    edges: [["A","C"], ["B","C"], ["C","F"]]
  };
  var wbs = {
    alt: "Simplified website work breakdown structure.",
    nodes: [
      { id: "root", label: "Website", x: 50, y: 13 },
      { id: "design", label: "Design", x: 24, y: 46 },
      { id: "build", label: "Build", x: 76, y: 46 },
      { id: "map", label: "Site map", x: 12, y: 80 },
      { id: "graphic", label: "Graphics", x: 39, y: 80 },
      { id: "code", label: "Code pages", x: 76, y: 80 }
    ],
    edges: [["root","design"],["root","build"],["design","map"],["design","graphic"],["build","code"]]
  };
  var stakeholderGrid = {
    alt: "Power and interest grid with four selectable quadrants.",
    nodes: [
      { id: "keep-informed", label: "Low power · high interest", x: 26, y: 25 },
      { id: "manage-closely", label: "High power · high interest", x: 73, y: 25 },
      { id: "monitor", label: "Low power · low interest", x: 26, y: 75 },
      { id: "keep-satisfied", label: "High power · low interest", x: 73, y: 75 }
    ],
    edges: []
  };
  window.MasteryModules = window.MasteryModules || [];
  window.MasteryModules.push({
    id: "inf3708",
    name: "INF3708",
    sourceFiles: [
      "inf3708-oct-nov-2021.json",
      "inf3708-oct-nov-2022-final.json",
      "inf3708-jan-feb-2023-supplementary.json",
      "inf3708-oct-nov-2024-final.json",
      "inf3708-jan-feb-2025-supplementary.json",
      "inf3708-assessment-1-2026.json",
      "test36.json"
    ],
    chapters: [
      chapter("1 · Introduction to Project Management", [
        topic("c1-project", "Projects and the triple constraint",
          "A project is temporary and creates a unique product, service or result. A project manager balances scope, time and cost while considering quality and sponsor satisfaction.",
          "PDF pp. 2–5",
          [term("Scope", "The work that must be completed."), term("Sponsor", "The person or group that provides direction and supports the project.")],
          ["An operation repeats routine work; a project has a defined start and finish.", "Changing scope can affect the cost, schedule and quality."],
          [quiz("c1a", "Which situation describes a project?", ["Sending the same daily status report every morning.", "Developing a new student registration application.", "Handling routine help-desk tickets."], 1,
            "The new application is a temporary effort that creates a unique outcome.", "A project can involve recurring tasks, but the project as a whole has a defined objective and end."),
           quiz("c1b", "A client adds features without extending time or budget. Which constraint has changed directly?", ["Scope", "Time", "Cost"], 0,
            "The amount of required work has increased: that is scope.", "The other constraints may be affected as a consequence, even if they were not directly changed.")]),
        topic("c1-program", "Project, program and portfolio",
          "A program coordinates related projects for combined benefits. A portfolio groups projects, programs and operations to achieve strategic business goals.",
          "PDF pp. 3, 6–7",
          [term("PMO", "Project Management Office: a group coordinating project management in the organisation.")],
          ["A portfolio answers whether the organisation is investing in the right work. Individual project management focuses on delivering a project."],
          [quiz("c1c", "A bank manages several related cybersecurity projects together to gain shared benefits. This is a:", ["Program", "Single task", "Work package"], 0,
            "Coordinating related projects for benefits not available separately is program management.", "A portfolio is broader and aligns initiatives to strategic goals.")])
      ]),
      chapter("2 · Project and IT Context", [
        topic("c2-systems", "Systems thinking and stakeholders",
          "IT projects exist within business, technology and organisational systems. Consider structural, human resources, political and symbolic organisational frames, not technology alone.",
          "PDF pp. 11–15",
          [term("Stakeholder", "A person or group that affects, or is affected by, the project."), term("Systems approach", "Considering interacting parts together rather than in isolation.")],
          ["Consult the people who will actually use the solution before adopting a new technology."],
          [quiz("c2a", "A college IT director plans mandatory tablets without asking lecturers or students. What is missing?", ["A systems view and stakeholder engagement.", "More programming languages.", "A final invoice."], 0,
            "The proposed technology affects learning, finances and people. Their needs must be understood.", "Technical suitability alone does not mean people will accept a project.", {caseStudy:"A college wants to introduce tablets for every student. The IT director checked the devices, but never asked faculty, students or finance about their needs."})]),
        topic("c2-life-cycle", "Predictive, adaptive and Scrum",
          "Predictive work defines scope, schedule and cost early. Adaptive approaches refine detailed scope by iteration. Scrum uses a product backlog, sprint backlog, short sprints, reviews and retrospectives.",
          "PDF pp. 15–18",
          [term("Sprint", "A short fixed period in which a team produces a usable increment."), term("Product owner", "The person who orders the product backlog by value.")],
          ["Hybrid projects combine predictive and adaptive practices where appropriate."],
          [quiz("c2b", "Requirements change frequently and the customer needs regular usable releases. Which life cycle fits this description?", ["Predictive", "Adaptive", "Operations only"], 1,
            "Adaptive delivery allows priorities and details to change between iterations.", "A sprint review examines the product increment; a retrospective examines how the team works.")])
      ]),
      chapter("3 · Project Management Process Groups", [
        topic("c3-groups", "The five process groups",
          "Project management processes move through initiating, planning, executing, monitoring and controlling, and closing. Monitoring and controlling overlaps the other groups.",
          "PDF pp. 19–21",
          [term("Initiating", "Formally recognising and starting a project or phase."), term("Closing", "Formal acceptance and completion of a project or phase.")],
          ["The process groups are not five isolated stages. Monitoring continues while work is performed."],
          [sequence("c3a", "Put the basic flow in order. Place monitoring and controlling conceptually alongside the flow.", ["Closing", "Executing", "Planning", "Initiating"],
            ["Initiating", "Planning", "Executing", "Closing"],
            "The overall sequence is initiate, plan, execute and close. Monitoring and controlling overlaps those activities.",
            "This ordering activity intentionally leaves out monitoring and controlling because it operates across the other groups.")]),
        topic("c3-deliverables", "Key planning outputs",
          "Initiating may produce a charter and stakeholder register. Planning develops documents such as the scope statement, WBS, schedule baseline, cost baseline and management plans.",
          "PDF pp. 20–24",
          [term("WBS", "Work Breakdown Structure: a hierarchy that divides project deliverables into manageable parts.")],
          ["A standard describes recommended practices. A methodology explains how a particular organisation performs them."],
          [quiz("c3b", "Which document formally authorises a new project?", ["Project charter", "Lessons-learned report", "Final acceptance certificate"], 0,
            "The charter establishes the project's authority and high-level objectives.", "The lessons-learned report usually records what the team learned for future projects.")])
      ]),
      chapter("4 · Project Integration Management", [
        topic("c4-financial", "Net present value and ROI",
          "NPV values future cash flows in today's money by using a discount rate. ROI compares the net discounted benefit against discounted costs.",
          "PDF pp. 26–29",
          [term("NPV", "Net Present Value: the total discounted benefits less total discounted costs."), term("Discount rate", "The rate used to convert a future value into a present value."), term("ROI", "Return on Investment.")],
          ["For full NPV from annual flows, calculate each cash flow divided by (1 + r) to the power of its year, then sum them.", "The worked examples here already supply the discounted totals."],
          [calc("c4a", "Calculate the project's NPV. Enter the monetary amount.", "NPV = discounted benefits − discounted costs",
              [{givens:["Discounted benefits = 516,000","Discounted costs = 243,200"],answer:272800,worked:"516,000 − 243,200 = 272,800."},
               {givens:["Discounted benefits = 150,000","Discounted costs = 125,000"],answer:25000,worked:"150,000 − 125,000 = 25,000."}],
              "Positive NPV means discounted benefits exceed discounted costs.", "Do not subtract undiscounted costs from discounted benefits; compare values on the same basis.",
              "Identify the two discounted totals, then subtract costs from benefits.",0.1),
           calc("c4b", "Calculate ROI as a percentage. Enter only the number, without the % sign.", "ROI (%) = (benefits − costs) ÷ costs × 100",
              [{givens:["Discounted benefits = 516,000","Discounted costs = 243,200"],answer:112.17,worked:"(516,000 − 243,200) ÷ 243,200 × 100 = approximately 112.17%."},
               {givens:["Discounted benefits = 180,000","Discounted costs = 120,000"],answer:50,worked:"60,000 ÷ 120,000 × 100 = 50%."}],
              "ROI expresses net value relative to the project's discounted cost.", "The denominator is total discounted costs, not total benefits.",
              "First calculate net discounted benefit. Divide by costs and multiply by 100.",0.2)]),
        topic("c4-scoring", "Weighted scoring and change control",
          "A weighted scoring model combines criteria with different importance levels. Integrated change control checks the effects of proposed project changes before approval or rejection.",
          "PDF pp. 28–31",
          [term("CCB", "Change Control Board: the group with authority to approve or reject specified project changes.")],
          ["Convert percentage weights to decimals before multiplying by each criterion score. Weights should total 100%."],
          [calc("c4c", "Calculate the total weighted score.", "Score = sum of (weight × criterion score)",
              [{givens:["Criterion A: weight 50%, score 80","Criterion B: weight 30%, score 90","Criterion C: weight 20%, score 70"],answer:81,worked:"0.50×80 + 0.30×90 + 0.20×70 = 40 + 27 + 14 = 81."},
               {givens:["Criterion A: weight 50%, score 65","Criterion B: weight 30%, score 85","Criterion C: weight 20%, score 95"],answer:77,worked:"32.5 + 25.5 + 19 = 77."}],
              "Higher-scoring projects meet the chosen weighted criteria more strongly.", "A weighted model only supports decisions when the selected criteria and weights make sense.",
              "Check that all weights add up to one before multiplying.",0.01),
           quiz("c4d", "A late feature request could change scope, budget and schedule. What is the appropriate process?", ["Integrated change control", "Delete the original plan without review", "Ignore the sponsor"], 0,
             "An authorised change process evaluates the impact and records the decision.", "A change can be valuable, but it still needs coordinated approval.", {caseStudy:"A customer asks for a new login method halfway through development. The change affects three teams and may add two weeks to the schedule."})])
      ]),
      chapter("5 · Project Scope Management", [
        topic("c5-wbs", "Work breakdown structures",
          "A WBS divides the whole project into deliverable-oriented components. The smallest manageable WBS element is called a work package. A WBS dictionary explains each element in more detail.",
          "PDF pp. 32–36",
          [term("Decomposition", "Breaking deliverables into smaller pieces."), term("Work package", "The lowest-level planned piece of work in a WBS.")],
          ["Analogy starts with a WBS from a similar past project; top-down starts with the whole project; bottom-up groups identified work into larger sections."],
          [Object.assign(quiz("c5a", "Select the lowest-level item in this simplified WBS.", ["Website", "Design", "Site map"], 2,
             "The site map is a leaf item and could be defined as a work package in this simplified example.",
             "A WBS shows deliverables and their breakdown, not necessarily the order in which activities take place."), {diagram:wbs}),
           quiz("c5b", "A manager adapts a WBS from an earlier, comparable project. Which method is this?", ["Analogy approach", "Bottom-up only", "Scope validation"], 0,
             "The analogy approach reuses a relevant past WBS as a starting point.", "Always adjust the old breakdown to fit the new project's own deliverables.")]),
        topic("c5-scope-control", "Requirements and scope creep",
          "Requirements describe necessary features or conditions. A requirements traceability matrix tracks them from their source through delivery and testing. Scope creep is uncontrolled growth in required work.",
          "PDF pp. 33–38",
          [term("RTM", "Requirements Traceability Matrix: a table linking each requirement to its source, delivery and validation.")],
          ["Validate scope through formal acceptance of completed deliverables; control scope by managing proposed changes."],
          [quiz("c5c", "Extra features are added repeatedly without approved change requests. This is an example of:", ["Scope creep", "Project closing", "Quality audit"], 0,
            "Work has expanded without proper scope control.", "A useful feature can still cause scope creep if the change is not managed.", {caseStudy:"A customer keeps asking developers directly for small extra features. Team members implement them without updating the agreed scope or budget."})])
      ]),
      chapter("6 · Project Schedule Management", [
        topic("c6-critical", "Critical path and slack",
          "The critical path is the longest duration path through a project activity network and determines the earliest finish. Slack is how long an activity can be delayed without delaying the project.",
          "PDF pp. 39–44",
          [term("Network diagram", "Shows activities and dependencies."), term("Slack / float", "Allowed delay without affecting the relevant next activity or completion date.")],
          ["A and B both precede C in the diagram. A = 5 days, B = 10 days and C = 7 days.", "The critical path can change during the project when actual task durations change."],
          [{id:"c6a",kind:"node",prompt:"Tap the activity that has five days of slack.",diagram:network,answer:"A",
            explanation:"Path A–C takes 12 days; B–C takes 17. A may be delayed by 5 days without changing the 17-day project finish.",
            studentNote:"The longest route is the critical path. Activities on a shorter parallel route can have float."},
           calc("c6b", "Calculate the total project duration in days.", "Project duration = longest full path",
             [{givens:["Path A–C: A = 5 days, C = 7 days","Path B–C: B = 10 days, C = 7 days"],answer:17,worked:"A–C = 12 days; B–C = 17 days. Longest = 17 days."},
              {givens:["Path A–C: A = 9 days, C = 4 days","Path B–C: B = 6 days, C = 4 days"],answer:13,worked:"A–C = 13; B–C = 10. Longest = 13 days."}],
             "The longest path determines earliest completion.", "Do not add parallel paths together; calculate each complete route.",
             "Add the durations on each route separately, then compare.",0.01)]),
        topic("c6-pert", "PERT time estimates",
          "PERT combines optimistic, most likely and pessimistic activity durations, giving the most likely estimate four times the weight of either extreme.",
          "PDF pp. 44–45",
          [term("O", "Optimistic (shortest reasonable duration)."),term("M", "Most likely duration."),term("P", "Pessimistic (longest reasonable duration).")],
          ["Use PERT when a simple single-point activity duration estimate has significant uncertainty."],
          [calc("c6c", "Find the PERT weighted estimate in days.", "PERT = (O + 4M + P) ÷ 6",
            [{givens:["O = 8 days","M = 10 days","P = 24 days"],answer:12,worked:"(8 + 4×10 + 24) ÷ 6 = 72 ÷ 6 = 12 days."},
             {givens:["O = 3 days","M = 6 days","P = 15 days"],answer:7,worked:"(3 + 4×6 + 15) ÷ 6 = 42 ÷ 6 = 7 days."}],
            "PERT is a weighted average, not a plain average of three estimates.",
            "Write the full names of O, M and P before substituting numbers; this avoids mixing them up.",
            "Multiply the most likely duration by four before adding.",0.01)])
      ]),
      chapter("7 · Project Cost Management", [
        topic("c7-evm", "Earned Value Management",
          "Earned Value Management connects planned work, completed work and actual spending. PV means planned value, EV means earned value and AC means actual cost.",
          "PDF pp. 52–54",
          [term("PV", "Planned Value: budgeted value of work scheduled."),term("EV", "Earned Value: budgeted value of work actually completed."),term("AC", "Actual Cost: what was actually spent.")],
          ["CV = EV − AC; SV = EV − PV; CPI = EV ÷ AC; SPI = EV ÷ PV.", "A negative CV or CPI below 1 generally means over budget. A negative SV or SPI below 1 generally means behind schedule."],
          [calc("c7a", "Calculate the cost variance (CV).", "CV = EV − AC",
            [{givens:["EV = 80,000","AC = 95,000"],answer:-15000,worked:"80,000 − 95,000 = −15,000."},
             {givens:["EV = 110,000","AC = 90,000"],answer:20000,worked:"110,000 − 90,000 = +20,000."}],
            "Negative cost variance indicates work completed cost more than its budgeted value.",
            "A negative result here is meaningful: do not remove the minus sign.",
            "Subtract the actual spending from the earned value.",0.01),
           calc("c7b", "Find CPI to two decimal places.", "CPI = EV ÷ AC",
            [{givens:["EV = 90,000","AC = 100,000"],answer:0.9,worked:"90,000 ÷ 100,000 = 0.90."},
             {givens:["EV = 105,000","AC = 100,000"],answer:1.05,worked:"105,000 ÷ 100,000 = 1.05."}],
            "CPI is a cost-efficiency index. Less than 1 means more spending than earned value.",
            "CPI is a ratio. Do not automatically write 90 when the question expects 0.90.",
            "Divide EV by AC, not the other way around.",0.005),
           calc("c7c", "Calculate schedule variance (SV).", "SV = EV − PV",
            [{givens:["EV = 60,000","PV = 75,000"],answer:-15000,worked:"60,000 − 75,000 = −15,000."},
             {givens:["EV = 85,000","PV = 80,000"],answer:5000,worked:"85,000 − 80,000 = 5,000."}],
            "Negative schedule variance means less work was earned than was planned at this point.",
            "SV in conventional EVM is expressed in value/currency units, not in days.",
            "PV is planned; EV is completed value.",0.01)]),
        topic("c7-budget", "Forecasts and reserves",
          "EAC forecasts total completion cost. Under a constant-CPI assumption, EAC = BAC ÷ CPI. Contingency reserves cover identified uncertainties; management reserves cover unknown uncertainties.",
          "PDF pp. 47–54",
          [term("BAC", "Budget at Completion: originally approved total budget."),term("EAC", "Estimate at Completion: projected final cost."),term("ETC", "Estimate to Complete: expected remaining cost.")],
          ["ETC = EAC − AC. This is only one of several accepted forecasting methods; use the method specified in the question."],
          [calc("c7d", "Estimate at completion (EAC) using the given CPI.", "EAC = BAC ÷ CPI",
            [{givens:["BAC = 100,000","CPI = 0.80"],answer:125000,worked:"100,000 ÷ 0.80 = 125,000."},
             {givens:["BAC = 120,000","CPI = 0.75"],answer:160000,worked:"120,000 ÷ 0.75 = 160,000."}],
            "If cost performance remains below 1, the projected total can exceed the approved budget.",
            "Only use this EAC formula when past CPI is assumed to continue.",
            "Divide the total approved budget by CPI.",0.01),
           quiz("c7e", "Which reserve is included in the cost baseline?", ["Contingency reserve", "Management reserve", "Neither reserve"], 0,
             "Contingency reserve covers known uncertainties and forms part of the cost baseline.",
             "Management reserve is controlled separately for unknown uncertainties.")])
      ]),
      chapter("8 · Project Quality Management", [
        topic("c8-quality", "Quality tools and cause analysis",
          "Project quality requires both meeting written requirements and being fit for actual use. Quality control tools include fishbone, control charts, check sheets, scatter diagrams, histograms, Pareto charts and flowcharts.",
          "PDF pp. 56–62",
          [term("Fishbone diagram", "Cause-and-effect diagram used to investigate possible root causes."),term("Pareto chart", "Shows categories ordered by frequency to identify major contributors.")],
          ["The seven-run rule flags seven consecutive points on one side of the mean, or consistently rising/falling, for investigation."],
          [quiz("c8a", "An online system receives complaints: login 55%, crashes 24%, reports 11%, other 10%. Which tool highlights the main categories first?", ["Pareto chart", "WBS", "RACI chart"], 0,
             "A Pareto chart orders complaint categories by frequency. Login plus crashes account for 79%.",
             "The 80/20 idea is a useful guide, not a rule that exactly 80% of problems always comes from exactly 20% of causes."),
           quiz("c8b", "Which diagram helps a team explore possible root causes of repeated login failures?", ["Fishbone / cause-and-effect", "Gantt chart", "Portfolio chart"], 0,
             "A fishbone diagram groups possible causes to support investigation.",
             "A fishbone helps generate possible causes; evidence is still needed to confirm the root cause.")]),
        topic("c8-sampling", "Sampling and Six Sigma",
          "Statistical sampling inspects a manageable subset of a larger population. Six Sigma focuses on improving processes using evidence. DMAIC stands for Define, Measure, Analyze, Improve and Control.",
          "PDF pp. 63–66",
          [term("Sample size", "Number of items examined from the population."),term("DPMO", "Defects Per Million Opportunities.")],
          ["The simplified sampling formula used in the summary is n = 0.25 × (certainty factor ÷ error)^2.", "Six Sigma's conventional target is 3.4 defects per million opportunities."],
          [calc("c8c", "Calculate the approximate sample size. Round to the nearest whole number.", "n = 0.25 × (z ÷ e)²",
            [{givens:["Certainty factor z = 1.960","Acceptable error e = 0.05"],answer:384,worked:"0.25 × (1.960 ÷ 0.05)² = 384.16, approximately 384."},
             {givens:["Certainty factor z = 1.645","Acceptable error e = 0.10"],answer:68,worked:"0.25 × (1.645 ÷ 0.10)² = 67.65, approximately 68."}],
            "A smaller allowable error usually requires a larger sample.",
            "Convert 5% to 0.05 before substitution. These examples use the simplified formula from the notes.",
            "Divide z by the decimal error, square it, then multiply by 0.25.",0.5),
           sequence("c8d", "Put the five DMAIC stages in order.",
             ["Control","Analyze","Measure","Define","Improve"],
             ["Define","Measure","Analyze","Improve","Control"],
             "First describe the problem; then collect data, find causes, improve the process and check that improvement lasts.",
             "Control is not the same as the initial measurement stage.")])
      ]),
      chapter("9 · Project Resource Management", [
        topic("c9-raci", "Responsibility assignment and RACI",
          "A RACI chart links project work with who performs it, signs it off, gives input and receives updates. It is a type of responsibility assignment matrix.",
          "PDF pp. 83–85",
          [term("R", "Responsible: performs the task."),term("A", "Accountable: owns the result and signs off."),term("C", "Consulted: provides input."),term("I", "Informed: receives updates.")],
          ["A clear RACI row has one Accountable person. Several people may be Responsible or Consulted."],
          [quiz("c9a", "Who is the single person answerable for final delivery in a RACI row?", ["Informed", "Accountable", "Consulted"], 1,
            "Accountable means ultimately answerable for the work or decision.", "Responsible and Accountable are different: doing the work is not necessarily signing it off.")]),
        topic("c9-level", "Resources and team development",
          "Overallocation occurs when the schedule demands more resource capacity than is available. Resource leveling adjusts activity timing to reduce that conflict.",
          "PDF pp. 85–88",
          [term("Resource histogram", "A chart of required resources over time."),term("Resource leveling", "Rescheduling work to resolve resource conflicts.")],
          ["Leveling can use available slack but may extend the project finish date.", "Tuckman's team stages are forming, storming, norming, performing and adjourning."],
          [quiz("c9b", "One analyst is booked for 70 hours of work in a 40-hour week. Which technique helps resolve this?", ["Resource leveling", "Scope validation", "Cost of quality"], 0,
             "Resource leveling changes work timing so resource demand becomes more manageable.",
             "Simply adding all the hours to a schedule does not make the analyst available.", {caseStudy:"Two dependent subprojects need the same analyst next week. One booking requests 30 hours and the other requests 40 hours, but the analyst only has 40 available."}),
           sequence("c9c", "Order the five Tuckman team stages.",
             ["Performing","Norming","Adjourning","Forming","Storming"],
             ["Forming","Storming","Norming","Performing","Adjourning"],
             "A team generally moves from introductions and conflict to cooperation, effective work and closure.",
             "A team can revisit earlier dynamics when members or circumstances change.")])
      ]),
      chapter("10 · Project Communications Management", [
        topic("c10-channels", "Communication channels",
          "The number of possible two-way connections between n project members rises rapidly as the team grows.",
          "PDF pp. 95–97",
          [term("n", "The number of people who could communicate directly with one another.")],
          ["Adding one person creates connections with each existing person; it does not add only one channel."],
          [calc("c10a", "How many potential communication channels are there?", "Channels = n(n − 1) ÷ 2",
             [{givens:["n = 6 people"],answer:15,worked:"6 × 5 ÷ 2 = 15 channels."},
              {givens:["n = 10 people"],answer:45,worked:"10 × 9 ÷ 2 = 45 channels."},
              {givens:["n = 4 people"],answer:6,worked:"4 × 3 ÷ 2 = 6 channels."}],
             "Each pair of people forms one possible two-way channel.",
             "Divide by two so that A–B and B–A are not counted as separate pairs.",
             "Multiply the number of people by one fewer person, then divide by two.",0.01)]),
        topic("c10-methods", "Interactive, push and pull communication",
          "Interactive communication exchanges information in both directions. Push sends information to recipients. Pull makes it available for people to access when needed.",
          "PDF pp. 97–100",
          [term("Status report", "Where the project stands at a point in time."),term("Progress report", "What was achieved during a period.")],
          ["An email being sent does not prove the recipient understood it."],
          [quiz("c10b", "A manager posts a document on a project website for staff to access when needed. Which method is this?", ["Push", "Pull", "Interactive"], 1,
            "A website is usually pull communication because people retrieve information when needed.",
            "A meeting is interactive; an emailed report is push.")])
      ]),
      chapter("11 · Project Risk Management", [
        topic("c11-emv", "Expected Monetary Value",
          "EMV combines the probability of each possible outcome with its monetary result. A decision tree lays out alternatives and their possible results.",
          "PDF pp. 106, 116–118",
          [term("Threat", "A possible negative effect on project objectives."),term("Opportunity", "A possible positive effect on project objectives.")],
          ["Multiply each branch outcome by its probability and sum the branch values. Keep losses negative.", "Each complete set of mutually exclusive outcome probabilities should sum to 1."],
          [calc("c11a", "Calculate the project EMV.", "EMV = sum of (probability × monetary outcome)",
            [{givens:["20% chance of gaining 300,000","80% chance of losing 40,000"],answer:28000,worked:"0.20×300,000 + 0.80×(−40,000) = 60,000 − 32,000 = 28,000."},
             {givens:["70% chance of gaining 60,000","20% chance of losing 50,000","10% chance of losing 20,000"],answer:30000,worked:"42,000 − 10,000 − 2,000 = 30,000."}],
            "EMV shows the probability-weighted monetary outcome across the possible branches.",
            "A large best-case payoff does not guarantee a larger EMV.",
            "Change each percentage to a decimal and show losses as negative values.",0.01)]),
        topic("c11-response", "Risk plans and strategies",
          "Negative-risk responses include avoid, accept, transfer, mitigate and escalate. Positive-risk strategies include exploit, share, enhance, accept and escalate.",
          "PDF pp. 119–123",
          [term("Contingency plan", "An agreed action if a known risk happens."),term("Residual risk", "Risk left after a response is applied."),term("Secondary risk", "A new risk created by a risk response.")],
          ["Contingency reserves cover known uncertainties; management reserves cover unknown uncertainties."],
          [quiz("c11b", "The team buys insurance for a potential equipment loss. Which threat response is this?", ["Transfer", "Exploit", "Ignore"], 0,
            "Insurance transfers some financial consequences to a third party.", "Transfer does not remove the event's probability; it changes who bears the consequences.", {caseStudy:"An organisation faces a chance of losing expensive project equipment in transit. The team chooses insurance to limit the financial impact if it happens."})])
      ]),
      chapter("12 · Project Procurement Management", [
        topic("c12-contracts", "Contract types and make-or-buy",
          "Procurement obtains goods or services from outside the project organisation. Fixed-price contracts set a defined price, cost-reimbursable contracts repay allowable actual costs plus fees, and time-and-material contracts pay for time and materials.",
          "PDF pp. 124–130",
          [term("SOW", "Statement of Work: describes required work so a supplier can respond and price it."),term("RFP", "Request for Proposal: seeks detailed supplier solutions."),term("RFQ", "Request for Quote: seeks quotes for clearly defined items.")],
          ["Choose contract types according to scope clarity and how cost risk is shared between buyer and seller."],
          [quiz("c12a", "A buyer needs a clearly specified deliverable at an agreed total price. Which contract family is described?", ["Fixed-price", "Cost-reimbursable", "No contract"], 0,
            "Fixed-price contracts specify the price for a well-defined product or service.", "The seller may price in risk, so an unclear scope is still a problem.")]),
        topic("c12-pta", "Point of Total Assumption",
          "In a fixed-price incentive fee contract, the Point of Total Assumption is the cost level after which the contractor bears the full cost of additional overruns.",
          "PDF p. 128",
          [term("Ceiling price", "Highest contract price under the agreement."),term("Target price", "Negotiated target payment."),term("Buyer share", "The buyer's fraction of the cost overrun sharing formula.")],
          ["Use the buyer or government share as a decimal, for example 75% = 0.75."],
          [calc("c12b", "Calculate PTA in thousands (K). Enter only the number.", "PTA = (ceiling price − target price) ÷ buyer share + target cost",
            [{givens:["Ceiling price = 1,250K","Target price = 1,100K","Buyer share = 75%","Target cost = 1,000K"],answer:1200,worked:"(1,250 − 1,100) ÷ 0.75 + 1,000 = 150 ÷ 0.75 + 1,000 = 1,200K."},
             {givens:["Ceiling price = 900K","Target price = 800K","Buyer share = 50%","Target cost = 700K"],answer:900,worked:"(900 − 800) ÷ 0.50 + 700 = 900K."}],
            "PTA is a threshold for the contractor's total overrun responsibility.",
            "Keep every monetary input in the same unit (K or whole currency values) before calculating.",
            "Subtract target price from ceiling first, then divide by buyer share.",0.01)])
      ]),
      chapter("13 · Project Stakeholder Management", [
        topic("c13-grid", "Power / interest grid",
          "Stakeholder analysis considers how much authority a person has and how interested they are in the project's outcome. A power/interest grid helps plan suitable engagement.",
          "PDF pp. 138–143",
          [term("Power", "Ability to influence project decisions."),term("Interest", "How closely the stakeholder cares about the project or its effects.")],
          ["Keep high-power, high-interest stakeholders closely engaged. The strategy can change as stakeholders or their needs change."],
          [{id:"c13a",kind:"node",prompt:"Tap the quadrant for a sponsor with high authority and high interest.",diagram:stakeholderGrid,
            answer:"manage-closely",
            explanation:"High-power, high-interest stakeholders are normally managed closely because they can strongly influence project decisions and are highly engaged.",
            studentNote:"The grid is about planning communication effort. Do not confuse power with interest."}]),
        topic("c13-engagement", "Stakeholder engagement and issues",
          "A stakeholder register records identification and project-relevant details. A stakeholder engagement plan addresses current and desired participation. An issue log records problems needing resolution.",
          "PDF pp. 140–149",
          [term("Stakeholder register", "List of identified stakeholders and their project-relevant information."),term("Issue log", "A record of issues, ownership, priority and resolution status.")],
          ["Engagement levels can include unaware, resistant, neutral, supportive and leading.", "Sensitive stakeholder assessments should be handled separately from widely shared project documents."],
          [quiz("c13b", "A senior sponsor is unaware of the project. Which action directly addresses this problem?", ["Brief the sponsor and plan appropriate engagement.", "Remove the sponsor from the register.", "Wait until project closing."], 0,
            "Stakeholder engagement starts by identifying, understanding and communicating with people who can affect the work.",
            "Monitoring stakeholder engagement is ongoing; stakeholder positions can change.", {caseStudy:"A newly appointed senior sponsor has decision-making power but has received no information about the project and has missed its planning meetings."}),
           quiz("c13c", "Where should the team track an unresolved requirements disagreement with an owner and priority?", ["Issue log", "WBS dictionary", "Final archive only"], 0,
            "An issue log tracks matters requiring action and resolution.",
            "A risk concerns an uncertain future event. An issue is something that already needs attention.")])
      ])
    ]
  });
}());
